_defaults:
  server:  Poinsts
  channel: points

standup_core:
  message_id: reminders.standup_core

standup_wizards:
  message_id: reminders.standup_wizards

timesheets:
  message_id: reminders.timesheets

